site_name: Roots Home
theme:
  name: material  # MkDocsで使うテーマ
  # --- 下記サイトを参考に調整 ---
  # https://squidfunk.github.io/mkdocs-material-insiders/setup/changing-the-colors/）
  palette:
    scheme: default  # ページのカラースキーム default、slate(ダークモード)
    primary: white  # メインカラー
    accent: deep orange  # リンクやボタンにカーソル当てたときのカラー
  font: 
    text: Noto Sans JP  # デフォルトはRoboto
    code: Roboto Mono  # コードブロックのフォント、デフォルトは Roboto Mono
  language: ja
  logo: img/site_logo.png  # ページ左上のロゴ
  favicon: img/site_favicon.png  # ファビコン（ブラウザのタブに表示されるやつ）
  features:
    - navigation.tabs  # ページ上にタブを付けられる
    - navigation.expand  # ページ階層を常に展開する
  # google_analytics:
  icon:
    repo: fontawesome/brands/github  # ページ右上に表示するリポジトリのアイコン
  
plugins:
  - search:  # 検索機能
      lang:
        - ja
        - en

# ページのフッターにつけるコンテンツ
extra:
  social:
     - icon: fontawesome/brands/twitter
       link: https://twitter.com/roots_ssl
       name: Roots Twitterアカウント
     - icon: fontawesome/brands/github
       link: https://github.com/SSL-Roots
       name: Roots GitHubページ
copyright: Copyright &copy; 2017 - 2020 Roots

# ページ右上に表示するリポジトリのリンク
repo_url: https://github.com/SSL-Roots/Roots_home
repo_name: SSL-Roots/Roots_home
edit_uri: edit/master/docs/  # 各ページに編集ボタン（鉛筆マーク）を表示。 "" で非表示

markdown_extensions:
  - attr_list  # 画像のalignを設定できる
  - pymdownx.tabbed  # タブで文章を切り替えられる
  - admonition  # Warningとかの飾り付けができる
  - pymdownx.highlight  # コードブロック用
  - pymdownx.superfences  # コードブロック用
  - pymdownx.emoji:  # アイコンが使える
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

site_url: https://ssl-roots.github.io/Roots_home/  # 404を正しく表示させるために必要

# 以下、ページ階層の設定
nav:
  - Home: index.md
  - ロボカップSSL:
    - ロボカップとは: robocup_ssl/about_robocup.md
    - ロボカップSSLの特徴: robocup_ssl/detail_robocup_ssl.md
    - ロボカップSSLに参加する: robocup_ssl/join_robocup_ssl.md
    - ロボットに必要な機能: robocup_ssl/required_functions_of_robots.md
    - 試合で必要なロボットの動き: robocup_ssl/required_actions_for_the_game.md
    - 人間の役割: robocup_ssl/human_roles.md
  - Roots:
    - Rootsとは: roots/detail_roots.md
    - 練習用フィールドセッティング: roots/field_setting.md
    - 設計データ2017: roots/robot_jo2017.md
    - 設計データ2019: roots/robot_jo2019.md
    - Rootsが参加したイベント:
      - MakerFaireTokyo2020: roots/events/202010_mft.md
    - 機械班:
      - 開発ツール: roots/mech/development_tools.md
      - ロボット本体の設計データ: roots/mech/detail_of_robot.md
      - ロボット制作費: roots/mech/cost_of_robot.md
    - 回路班:
      - 開発ツール: roots/elec/development_tools.md
      - メイン基板:
        - メイン基板について: roots/elec/main_board/detail_main_pcb.md
        - ファームウェアの書き込み: roots/elec/main_board/writing_mbed_firmware.md
        - プログラムについて: roots/elec/main_board/mainboard_program.md
      - モータドライバ基板:
        - モータドライバ基板について: roots/elec/motor_driver/detail_motor_driver_pcb.md
        - ファームウェアの書き込み: roots/elec/motor_driver/writing_motor_driver_firmware.md
      - ボールセンサ基板: roots/elec/detail_ball_sensor_pcb.md
      - 昇圧基板: roots/elec/detail_booster_pcb.md
      - エンコーダ基板: roots/elec/detail_encoder_pcb.md
      - Elecrowへの基板発注方法: roots/elec/how_to_order_elecrow_pcb.md
    - 戦略ソフト班: 
      - 開発ツール: roots/soft/development_tools.md
  - もっと小さいロボット:
    - コンセプト: vssl/concept.md
  - リンク集: links.md
  - このウェブサイトのライセンス: license.md
    
